site_name: AquaPack Robotics SW9 Documentation
extra_css:
  - stylesheets/extra.css
extra_javascript:
  - javascript/zooming.min.js
  - javascript/activate.js
theme:
  name: material
  logo: img/logo.png
  favicon: img/favicon.png
  features:
    - navigation.tabs
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: custom
      accent: custom
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: custom
      accent: custom
markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences
extra:
  generator: false
copyright: AquaPack Robotics &copy; 2023 Released under <a id="footer-link" href="https://creativecommons.org/licenses/by-sa/4.0/">CC BY-SA 4.0</a>
nav:
  - Home: index.mdl
  - Electrical:
      - Microcontroller Architecture: electrical/microcontroller-architecture.md
  - тод Return to general documentation: https://ncsurobotics.github.io/
