title: SeaWolf IX System Architecture {
  near: top-left
  shape: text
  style: {
    font-size: 29
    bold: true
  }
}

battery: 4S LiPo

test: Under Test Conditions {
  tether: Ethernet Tether
  surface: Surface
}

locomotion: Motors {
  esc: ESC (x6)
  thrusters: Thruster (T200 x5, T500 x1)
  ctrl: Control Board
}

ex: Expansion Boards {
  msys: Manipulation Systems Board
  ac: Acoustics
}

backplane: Backplane {
  i2c: I2C
  lights: LEDs

  regulators: Regulators {
    twelve: 12V
    five: 5V
    three: 3V3
  }
}

sensors: Sensors {
  modem: Acoustics Modem
  dvl: DVL
  sonar: Active Sonar
  cam: Cameras
  leak: Leak Sensors
  hydro: Hydrophones
}

switching: Switching {
    sys: System Power
    swkill: Software Kill
    hwkill: Hardware Kill
}

computer: Computer {
    orin: Jetson Orin Nano
    usb: USB Hub
}

manipulators: Manipulators {
    dropper: Dropper
    torpedo: Torpedo
    grabber: Grabber
}

ex.msys -> manipulators.dropper
ex.msys -> manipulators.torpedo
ex.msys -> manipulators.grabber

battery -> switching.sys

switching.sys -> backplane.regulators.twelve
switching.sys -> locomotion.esc
switching.swkill -> switching.hwkill
locomotion.esc -> locomotion.thrusters
locomotion.thrusters <- switching.hwkill

backplane.regulators.twelve -> backplane.regulators.five
backplane.regulators.twelve -> backplane.regulators.three
backplane.regulators.twelve -> computer.orin
backplane.regulators.twelve -> ex
backplane.regulators.twelve -> backplane.lights
backplane.regulators.twelve -> sensors.modem
backplane.regulators.twelve -> sensors.dvl
backplane.regulators.twelve -> sensors.sonar

backplane.regulators.five -> ex
backplane.regulators.five -> computer.usb

backplane.regulators.three -> ex
backplane.regulators.three -> backplane.i2c

backplane.i2c <-> ex
backplane.i2c -> sensors.leak

computer.usb <-> computer.orin
computer.usb <-> sensors.cam
computer.usb <-> locomotion.ctrl

computer.orin -> switching.swkill

locomotion.ctrl -> locomotion.esc

sensors.hydro -> ex.ac

test.surface <-> test.tether
test.tether <-> computer.orin
